name: brewery
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  bloc_concurrency: ^0.2.0
  build_runner: ^2.3.3
  cached_network_image: ^3.2.3
  dio: ^5.1.0
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.7.0
  fluttertoast: ^8.2.1
  google_sign_in: ^6.0.2
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
